
GET https://hospital-project-api.onrender.com/api/users
###
GET https://hospital-project-api.herokuapp.com/api/users/login
###
POST https://hospital-project-api.herokuapp.com/users 
Content-Type: application/json

{
	"email" : "tung2082002@gmail.com",
	"password": "20082002"
}
###

POST https://hospital-project-api.herokuapp.com/users/login 
Content-Type: application/json

{
	"email" : "tung2082002@gmail.com",
	"password": "1111"
}

### 

POST https://hospital-project-api.herokuapp.com/api/users/login
Content-Type: application/json

{
	"email" : "doctor@gmail.com",
	"password": "11111111"
}
###

POST https://hospital-project-api.herokuapp.com/doctors/delete/20225

###

GET https://hospital-project-api.onrender.com/doctors

###

GET https://hospital-project-api.herokuapp.com/appointments